version: '3'

services:
  poll:
    build: ./poll
    links:
      - redis
    ports:
      - "5000:80"
    networks:
      - poll-tier
    restart: on-failure

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    environment:
      - POLL_HOSTNAME=poll
      - WORKER_HOSTNAME=worker
    networks:
      - poll-tier
      - back-tier
    restart: always

  worker:
    build: ./worker
    links:
      - redis
      - db
    networks:
      - back-tier
    environment:
      - DB_HOSTNAME=db
      - REDIS_HOSTNAME=redis
    restart: always

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - WORKER_HOSTNAME=worker
      - RESULT_HOSTNAME=result
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    networks:
      - result-tier
      - back-tier
    restart: always

  result:
    build: ./result
    links:
      - db
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - DB_HOSTNAME=db
    restart: always

volumes:
  db-data:
    driver: local

networks:
  poll-tier:
    driver: bridge
  result-tier:
    driver: bridge
  back-tier:
    driver: bridge
